[build]
pre-build = [
    "apt-get update && apt-get install --assume-yes ",
    "apt-get update && apt-get install -y pkg-config libudev-dev libasound2-dev",
]

# Mac OS
[target.x86_64-apple-darwin]
pre-build = []

# Win OS
[target.x86_64-pc-windows-msvc]
pre-build = []

# raspberryPI OS 64bits
[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes ",
    "apt-get update && apt-get install -y pkg-config libudev-dev:$CROSS_DEB_ARCH libasound2-dev:$CROSS_DEB_ARCH",
]

# raspberryPI OS 32bits
[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes ",
    "apt-get update && apt-get install -y pkg-config libudev-dev:$CROSS_DEB_ARCH libasound2-dev:$CROSS_DEB_ARCH",
]