/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./../components/global/app/AppBar.vue')['default']
    AppDrawer: typeof import('./../components/global/app/AppDrawer.vue')['default']
    AppLink: typeof import('./../components/global/app/AppLink.vue')['default']
    AppLoader: typeof import('./../components/global/app/AppLoader.vue')['default']
    AppToaster: typeof import('./../components/global/app/AppToaster.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomePage: typeof import('./../pages/HomePage.vue')['default']
    I18nSwitch: typeof import('./../components/global/i18n/I18nSwitch.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    IndexPage: typeof import('./../pages/IndexPage.vue')['default']
    LanBroken: typeof import('./../components/global/connexion/LanBroken.vue')['default']
    LanControl: typeof import('./../components/global/connexion/LanControl.vue')['default']
    LanguageSwitcher: typeof import('./../components/global/i18n/LanguageSwitcher.vue')['default']
    LanSettingsForm: typeof import('./../components/global/connexion/LanSettingsForm.vue')['default']
    MainMenu: typeof import('./../components/global/menus/MainMenu.vue')['default']
    MainMenuList: typeof import('./../components/global/menus/MainMenuList.vue')['default']
    NotFoundPage: typeof import('./../pages/NotFoundPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPage: typeof import('./../pages/SettingsPage.vue')['default']
    SvgArduino: typeof import('./../components/global/icons/SvgArduino.vue')['default']
    SvgLed: typeof import('./../components/global/icons/SvgLed.vue')['default']
    SvgMotor: typeof import('./../components/global/icons/SvgMotor.vue')['default']
    SvgRobot: typeof import('./../components/global/icons/SvgRobot.vue')['default']
    SvgRobotBroken: typeof import('./../components/global/icons/SvgRobotBroken.vue')['default']
    SvgServo: typeof import('./../components/global/icons/SvgServo.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
