#!/bin/bash

# Function to install avrdude if it doesn't exist
install_avrdude() {
    echo "avrdude is not installed. Installing avrdude..."
    sudo apt-get update
    sudo apt-get install -y avrdude
}

# Check if avrdude is installed
if ! command -v avrdude &> /dev/null
then
    install_avrdude
fi

# Stop hermes-studio service
sudo systemctl stop hermes.service

# Upload hex files to Arduino with avrdude
if command -v avrdude &> /dev/null
then
    avrdude -p m2560 -c stk500v2 -P /dev/ttyACM0 -b 115200 -D -U flash:w:/home/pi/Desktop/hermes-studio/firmwares/firmware.hex
    avrdude -p m2560 -c stk500v2 -P /dev/ttyACM1 -b 115200 -D -U flash:w:/home/pi/Desktop/hermes-studio/firmwares/firmware.hex
else
    echo "avrdude is not installed and could not be installed automatically. Please install it manually."
    exit 1
fi

# Restart hermes service
sudo systemctl restart hermes.service